package com.zzw.dianping.dal;

import com.zzw.dianping.model.categoryModel;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
public interface categoryModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 21 10:59:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    List<categoryModel> selectAll();
    Integer countAllCategory();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 21 10:59:54 CST 2019
     */
    int insert(categoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 21 10:59:54 CST 2019
     */
    int insertSelective(categoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 21 10:59:54 CST 2019
     */
    categoryModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 21 10:59:54 CST 2019
     */
    int updateByPrimaryKeySelective(categoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Jul 21 10:59:54 CST 2019
     */
    int updateByPrimaryKey(categoryModel record);
}